
dict_station = {
            "montaudran": ("12", "Toulouse", "montaudran"),
            "colomiers_zi_enjacca": ("24", "Colomiers", "zi-enjacca"),
            "parc_maourine": ("62", "Toulouse", "parc-maourine"),
            "marengo": ("2", "Toulouse", "marengo"),
            "pech_david": ("13", "Toulouse", "pech-david"),
            "compans_cafarelli": ("42", "Toulouse", "parc-compans-cafarelli"),
            "fondeyre": ("58", "Toulouse", "fondeyre"),
            "paul_sabatier": ("37", "Toulouse", "universite-paul-sabatier"),
            "mondouzil": ("19", "Mondouzil", "mairie"),
            "basso_cambo": ("8", "Toulouse", "basso-cambo"),
            "soupetard": ("11", "Toulouse", "soupetard"),
            "mons_epuration": ("31", "Mons", "station-epuration"),
            "saint_jory_beldou": ("33", "Saint-Jory", "chapelle-beldou"),
            "jardin_des_plantes": ("38", "Toulouse", "parc-jardin-des-plantes"),
            "la_machine_af": ("48", "Toulouse", "la-machine-af"),
            "life_marechal_juin": ("63", "Toulouse", "life-marechal-juin"),
            "metropole": ("1", "Toulouse", "metropole"),
            "mondonville_ecole": ("20", "Mondonville", "ecole"),
            "teso": ("34", "Toulouse", "teso"),
            "zi_thibaud": ("40", "Toulouse", "zi-thibaud"),
            "busca": ("3", "Toulouse", "busca"),
            "pibrac_bouconne": ("23", "Pibrac", "bouconne-centre-equestre"),
            "life_hall1": ("5", "Toulouse", "life-hall-1"),
            "nakache": ("5", "Toulouse", "nakache"),
            "casselardit": ("41", "Toulouse", "avenue-de-casselardit"),
            "st_exupery": ("45", "Toulouse", "st-exupery"),
        }